# Remove Files
- name:       Remove unneeded packages
  apt:
    state: absent
    purge: yes
    name: "{{ item }}"
  with_items:
    - transmission
    - hexchat
    - thunderbird
    - pidgin
    - cron-apt
    - gnome-screensaver
    - variety
    - cheese
    - shotwell
    - screen

# Install Files
- name:       Install needed packages
  apt:
    state: present
    name: "{{ item }}"
  with_items:
  # screensaver
  - xscreensaver
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-dizzy
  - xscreensaver-screensaver-webcollage
  - xscreensaver-data-extra
  - rss-glx
  # Core Desktop Tools
  - python-software-properties
  - htop
  - wget
  - curl
  - nano
  - python-pycurl
  - firefox
  - gnome-tweak-tool
  - python-pip
  # - tor-browser
  - nfs-common
  - virtualbox
  - virtualbox-dkms
  - virtualbox-ext-pack
  - virtualbox-guest-additions-iso
  - glusterfs-client
#Developer packages. These might end up being in their own groups
  - tmux
  - git