---
# Enable UFW
- name: Enalbe UFW
  ufw: state=enabled

# Allow OpenSSH
- name: UFW - Allow OpenSSH
  ufw: rule=allow name=OpenSSH

# Allow all access to tcp port 80:
- name: UFW - Allow Web
  ufw: rule=allow port=80 proto=tcp

# Allow all access from RFC1918 networks to this host:
- name: UFW - Allow access where the source is a private IP
  ufw: rule=allow src={{ item }}
  with_items:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
