---
- include: groups.yml
- include: firewall.yml

- name:    Make Profiles directory
  file:
    path:  /opt/profiles
    state: directory

- name:    Make Provision directory
  file:
    path:  /opt/provision/bin/
    state: directory



# - name: Update GDM login

# - name: Update LDM login