---

- name:         Running generic Configurations and Commands
  include_tasks:      "{{ Class_Room_Configuration }}"
  with_items:
    - "all_system.yml"
    - "all_packages.yml"
    - "firewall.yml"
  loop_control:
    loop_var:   Class_Room_Configuration

# - import_tasks: groups.yml
# - import_tasks: firewall.yml
# - import_tasks: home_sync.yml

- name:    Make Profiles directory
  file:
    path:  /opt/profiles
    state: directory

- name:    Make Provision directory
  file:
    path:  /opt/provision/bin/
    state: directory

- name: Copy autologin Custom GDM config
  copy:
    src: files/custom.conf
    dest: /etc/gdm3/custom.conf


# - name: Update GDM login

# - name: Update LDM login