---
example:
  script:
    - echo localhost > inventory
    # Check syntax
    - ansible-playbook --syntax-check -i inventory ansible/test.yml
    # First run
    - ansible-playbook -i inventory ansible/test.yml --connection=local

    # Idempotence
    - >
      ansible-playbook -i inventory ansible/test.yml --connection=local
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

