---
sudo: required

env:
#  - distribution: centos
#    version: 6
#    init: /sbin/init
#    run_opts: ""
#    playbook: test.yml
#  - distribution: centos
#    version: 7
#    init: /usr/lib/systemd/systemd
#    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
#    playbook: centos-7-test.yml
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    playbook: test.yml
  # - distribution: ubuntu
  #   version: 12.04
  #   init: /sbin/init
  #   run_opts: ""
  #   playbook: test.yml

services:
  - docker


before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'


language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:

  ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  # We'll add some commands to test the role here.
  # Run the role/playbook with ansible-playbook.
- "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
