---
all:
    hosts:
        # Classroom[01:18].classroom.library.wpl.lib.in.us
        Classroom01.classroom.library.wpl.lib.in.us
        Classroom10.classroom.library.wpl.lib.in.us
    ansible_user: it
    ansible_ssh_private_key_file: /home/joe/.ssh/ansible
    deploy_target: it