---
- hosts: all
  become: true
  pre_tasks:
    - name: Install Keyfile to allow for easier management
      authorized_key:
        user: it
        key: "{{ lookup('file', '/home/joe/.ssh/ansible.pub') }}"
        path: '/etc/ssh/authorized_keys/it'
        manage_dir: no


    - name: Ensure apt config file exsists
      file:
        path: /etc/apt/apt.conf
        state: touch
        mode: "u=rw,g=r,o=r"

    - name:           Ensure Cache is enabled
      lineinfile:
        dest:         /etc/apt/apt.conf
        regexp:       "^Acquire::http { Proxy \"http://wpl-docker04.vm.library.wpl.lib.in.us:3142\"; };"
        line:         "Acquire::http { Proxy \"http://wpl-docker04.vm.library.wpl.lib.in.us:3142\"; };"
        backup:       yes

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Update System
      apt: upgrade=dist
      when: ansible_os_family == "Debian"
  roles:
    # - base
    # - classroom
    # - arduino
    # - minecraft
    # - vcabourdin.chrome
    # - mongrelion.docker
    # - docker-syncthing

  vars_files:
    - vars/vault.yml
    - vars/firewall.yml
  #
  # post_tasks:
  #   - name: Reboot Computers
  #     shell: ( sleep 3 && /sbin/reboot & )
  #     async: 0
  #     poll: 0
  #     ignore_errors: true
  #
  #   - name: Wait for the server to finish rebooting
  #     become: false
  #     local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

# Modules from https://github.com/JBKahn/provisioning-local.git
