---
- hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Update System
      apt: upgrade=dist
      when: ansible_os_family == "Debian"


  roles:
    - arduino

  #    - reboot

  vars_files:
    - vars/vault.yml


# Modules from https://github.com/JBKahn/provisioning-local.git
