---
- hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    # - name: install python 2
    #   shell: apt install -y python-minimal
    #   creates: /usr/bin/python
  vars_files:
    - vars/vault.yml


- hosts: all
  become: true
  pre_tasks:
    - name: Setup apt-cacher
      copy:
        src: files/01proxy
        dest: /etc/apt/apt.conf.d/01proxy
        backup: true

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Update System
      apt: upgrade=dist
      when: ansible_os_family == "Debian"s
  roles:
    # - bug-fixes
    - base
    - geerlingguy.git
    - classroom
    - arduino
    - minecraft
    - geerlingguy.pip
    - geerlingguy.docker
    # - geerlingguy.firewall
    # - geerlingguy.glusterfs
    # - cmprescott.chrome
     - docker-syncthing
     - docker-ping


  vars_files:
    - vars/vault.yml
    - vars/firewall.yml
  #
  post_tasks:
    - name: Reboot Computers
      shell: ( sleep 3 && /sbin/reboot & )
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for the server to finish rebooting
      become: false
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

# # Modules from https://github.com/JBKahn/provisioning-local.git
