---
# http://patorjk.com/software/taag/#p=display&c=bash&f=Epic&t=Wallpaper
#   _______  _______  _______          _________ _______ _________ _______  _
#  (  ____ )(  ____ )(  ___  )|\     /|\__   __/(  ____ \\__   __/(  ___  )( (    /|
#  | (    )|| (    )|| (   ) || )   ( |   ) (   | (    \/   ) (   | (   ) ||  \  ( |
#  | (____)|| (____)|| |   | || |   | |   | |   | (_____    | |   | |   | ||   \ | |
#  |  _____)|     __)| |   | |( (   ) )   | |   (_____  )   | |   | |   | || (\ \) |
#  | (      | (\ (   | |   | | \ \_/ /    | |         ) |   | |   | |   | || | \   |
#  | )      | ) \ \__| (___) |  \   /  ___) (___/\____) |___) (___| (___) || )  \  |
#  |/       |/   \__/(_______)   \_/   \_______/\_______)\_______/(_______)|/    )_)
#
#   _______  _        ______     _______  _______ _________          _______
#  (  ___  )( (    /|(  __  \   (  ____ \(  ____ \\__   __/|\     /|(  ____ )
#  | (   ) ||  \  ( || (  \  )  | (    \/| (    \/   ) (   | )   ( || (    )|
#  | (___) ||   \ | || |   ) |  | (_____ | (__       | |   | |   | || (____)|
#  |  ___  || (\ \) || |   | |  (_____  )|  __)      | |   | |   | ||  _____)
#  | (   ) || | \   || |   ) |        ) || (         | |   | |   | || (
#  | )   ( || )  \  || (__/  )  /\____) || (____/\   | |   | (___) || )
#  |/     \||/    )_)(______/   \_______)(_______/   )_(   (_______)|/
#
#   _______  _        _______  _______  _______  _______  _______  _______  _______
#  (  ____ \( \      (  ___  )(  ____ \(  ____ \(  ____ )(  ___  )(  ___  )(       )
#  | (    \/| (      | (   ) || (    \/| (    \/| (    )|| (   ) || (   ) || () () |
#  | |      | |      | (___) || (_____ | (_____ | (____)|| |   | || |   | || || || |
#  | |      | |      |  ___  |(_____  )(_____  )|     __)| |   | || |   | || |(_)| |
#  | |      | |      | (   ) |      ) |      ) || (\ (   | |   | || |   | || |   | |
#  | (____/\| (____/\| )   ( |/\____) |/\____) || ) \ \__| (___) || (___) || )   ( |
#  (_______/(_______/|/     \|\_______)\_______)|/   \__/(_______)(_______)|/     \|
#
- hosts: all
  become: true
  pre_tasks:
#    - name: install requirements from ansible galaxy
#      command: ansible-galaxy install -r requirements.yml --ignore-errors

    - name: Install Keyfile to allow for easier management
      authorized_key:
        user: it
        key: "{{ lookup('file', '/home/joe/.ssh/remote.pub') }}"
        path: '/etc/ssh/authorized_keys/it'
        manage_dir: no

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Update System
      apt: upgrade=dist
      when: ansible_os_family == "Debian"

  roles:
    - base
    - arduino
    - minecraft
    - vcabourdin.chrome
    - mjanser.powerline
   # - { role: hubisan.virtualbox }

  vars_files:
    - vars/vault.yml
    - vars/firewall.yml
    - vars/powerline.yml
    - vars/syncthing.yml


  post_tasks:
    - name: Make Profiles directory
      file:
        path: /mnt/profiles
        state: directory
        mode: 0755
        recurse: yes

    - name: Mount Profiles Read only
      mount:
        name: /mnt/profiles
        src: wpl-backup:/mnt/backups/storage/profiles
        fstype: nfs
        opts: ro,rsize=8192,wsize=8192,timeo=15
        state: present

#    - name: Give Public back their home
#      file: path=/home/public/ owner=public group=public mode=0755

  #  - name: Reboot Computers
  #    command: /sbin/shutdown -r +1
  #    async: 0
  #    poll: 0
  #    ignore_errors: true
# Modules from https://github.com/JBKahn/provisioning-local.git
