---
- hosts: all
  become: true
  pre_tasks:
    - name: Install Keyfile to allow for easier management
      authorized_key:
        user: it
        key: "{{ lookup('file', '/home/joe/.ssh/remote.pub') }}"
        path: '/etc/ssh/authorized_keys/it'
        manage_dir: no

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"

    - name: Update System
      apt: upgrade=dist
      when: ansible_os_family == "Debian"

    # This is for Ansible 2.1
    # - name: Cleaning up System
    #  apt: autoremove=true
    #  when: (ansible_version.major == 2) and (ansible_version.minor >=1) and (ansible_os_family == "Debian")

  roles:
    - base
#    - developer
    - arduino
    - minecraft
    - vcabourdin.chrome
  #  - mglaman.atom
    - mjanser.powerline
  #    - reboot

  vars_files:
    - vars/vault.yml
    - vars/firewall.yml
    - vars/powerline.yml
    - vars/atom.yml
    - vars/syncthing.yml


  post_tasks:
    - name: Give Public back their home
      file: path=/home/public/ owner=public group=public mode=0755

  #  - name: Reboot Computers
  #    command: /sbin/shutdown -r +1
  #    async: 0
  #    poll: 0
  #    ignore_errors: true
# Modules from https://github.com/JBKahn/provisioning-local.git
