---
- hosts: localhost
  remote_user: root
  roles:
    - base
    - arduino
    - minecraft
  vars_files:
    - vars/vault.yml
    - vars/firewall.yml
  post_tasks:
    - name: Give Public back their home
      file: path=/home/public/ owner=public group=public mode=0755
