---
# tasks file for docker-syncthing

- name: Install python-pip
  apt:
      name: python-pip
      state: present
- name: Install docker-py
  pip:
      name: docker-py

- name: Create paths
  file:
    path: "/docker/syncthing/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - data
    - config

- name: Start syncthing container
  docker_container:
    name: syncthing
    image: joeybaker/syncthing
    state: started
    restart_policy: unless-stopped
    recreate: no
    exposed_ports:
        - 2200
        - 8080
        - 21027/udp
    published_ports:
        - 2200:2200
        - 21027:21027/udp
        - 8080:8080
    volumes:
        - '/docker/syncthing/data/sync:/srv/data'
        - '/docker/syncthing/config:/srv/config'

- name: Open Ports for transmission UFW
  ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    rule: allow
  with_items:
    - "{{ docker_ports }}"
  notify: Restart UFW
  when: ansible_distribution == "Ubuntu"
