---
# tasks file for docker-syncthing

- name: Install python-pip
  apt:
      name: python-pip
      state: present
- name: Install docker-py
  pip:
      name: docker-py

- name: Create config paths
  file:
    path: "/docker/containers/syncthing/{{ item }}"
    state: directory
    mode: 0775
    owner: 911
    group: docker
    recurse: yes
  with_items:
    - config

- name: Create data paths
  file:
    path: "/docker/containers/syncthing/{{ item }}"
    state: directory
    mode: 0775
    owner: 1000
    group: 1000
    recurse: yes
  with_items:
    - data
    - data/sync
    - data/public_profile
    - data/tapet

- name: Remove Old Paths
  file:
    path: "/docker/containers/syncthing/{{ item }}"
    state: absent
  with_items:
    - sync
    - public_profile
    - tapet



- name: Start syncthing container
  docker_container:
    name: syncthing
    image: linuxserver/syncthing
    state: started
    restart_policy: always
    recreate: yes
    pull: true
    exposed_ports:
        - 22000
        - 8384
        - 21027/udp
    published_ports:
        - 22000:22000
        - 21027:21027/udp
        - 8384:8384
    volumes:
        - '/docker/containers/syncthing/data/sync:/mnt/sync'
        - '/docker/containers/syncthing/data/public_profile:/mnt/public_profile'
        - '/docker/containers/syncthing/data/tapet:/mnt/tapet'
        - '/docker/containers/syncthing/config:/config'
    env:
        PGID: 1000
        PUID: 1000
        TZ: America/Chicago

- name: Open Ports for transmission UFW
  ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    rule: allow
  with_items:
    - "{{ docker_ports }}"
  notify: Restart UFW
  when: ansible_distribution == "Ubuntu"
