---

- name: Install Arduino -_-
  # Install Debian Specific files.
  apt: state=present name={{item}}
  with_items:
    - auduino
    - auduino-core

- name: ArduBlockTool Creating Directory
  file:
    path: "/home/{{item}}/arduino/tools/ArduBlockTool/tool/"
    state: directory
    mode: 0755
  with_items:
    - "{{arduino_users}}"

- name: Placing ArduBlockTool into IDE
  copy:
    src: "files/ardublock-all.jar"
    dest: "/home/{{item}}/arduino/tools/ArduBlockTool/tool/"
    mode: 0755
  with_items:
    - "{{arduino_users}}"
  register: file_copied

- name: Placing Arduino Files into IDE
  copy:
    src: "files/ardublock-all.jar"
    dest: "/home/{{item}}/arduino/tools/ArduBlockTool/tool/"
    mode: 0755
  with_items:
    - "{{arduino_users}}"
  register: file_copied



#- name: Placing Arduino Files into IDE
  # Synchronization without any --archive options enabled
#  synchronize:
#    src: files/
#    dest: /home/{{item}}/arduino/tools
#    archive: no
#    recursive: yes
#  with_items:
#    - "{{arduino_users}}"
#  register: file_copied


- name: Fixing Permissions Directory
  file: path=/home/{{item}}/arduino/tools/ArduBlockTool/tool owner={{item}} group={{item}} recurse=yes
  with_items:
    - "{{arduino_users}}"
- include: permissions.yml
