---

- name: Install Arduino -_-
  # Install Debian Specific files.
  apt: state=present name={{item}}
  with_items:
    - arduino
    - arduino-core

- name: ArduBlockTool Creating Directory
  file:
    path: "/home/{{item}}/arduino/tools/ArduBlockTool/tool/"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_items:
    - "{{arduino_users}}"

- name: Placing ArduBlockTool into IDE
  copy:
    src: "files/arduino//ardublock-all.jar"
    dest: "/home/{{item}}/arduino/tools/ArduBlockTool/tool/"
    mode: 0755
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register: file_copied


- name: Placing Arduino Files into IDE
  unarchive: 
    src: "files/ArduBlockTool.tar.gz" 
    dest: "/home/{{ item }}/arduino/tools/ArduBlockTool/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register: file_copied


- name: Arduino Link on Desktop
  copy:
    src: "files/desktop/arduino.desktop"
    dest: "/home/{{item}}/Desktop/"
    mode: 0755
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register: file_copied


- name: Create Aruino Global Install
  file: 
    path: "/opt/{{arduino_version}}" 
    state: directory 
    mode: 0755



- name: Installing Updated Arduino
  unarchive: 
    src: "files/{{arduino_version}}-linux64.tar.xz" 
    dest: "/opt/{{arduino_version}}"  #change this in the vars file


- name: Fixing Permissions Directory
  file: 
    path: "/home/{{item}}/arduino/tools/ArduBlockTool/tool" 
    owner: "{{item}}" 
    group: "{{item}}" 
    recurse: yes
  with_items:
    - "{{arduino_users}}"


- include: permissions.yml
