---
- name:         Install Arduino -_-
  # Install Debian Specific files.
  apt:
    state:      present
    name:       "{{ item }}"
  with_items:
    - arduino
    - arduino-core

- name:         ArduBlockTool Creating Directory
  file:
    path:       "/home/{{item}}/Arduino/tools/ArduBlockTool/tool/"
    state:      directory
    owner:      "{{ item }}"
    group:      "{{ item }}"
    mode:       0755
  with_items:
    - "{{arduino_users}}"

- name:         Placing ArduBlockTool into IDE
  copy:
    src:        "files/arduino/ardublock-all.jar"
    dest:       "/home/{{item}}/Arduino/tools/ArduBlockTool/tool/"
    mode:       0755
    owner:      "{{ item }}"
    group:      "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register:     file_copied


- name:         Placing Arduino Files into IDE
  unarchive:
    src:        "files/ArduBlockTool.tar.gz"
    dest:       "/home/{{ item }}/Arduino/tools/ArduBlockTool/"
    owner:      "{{ item }}"
    group:      "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register:     file_copied


- name:         Copy Adafruit udev Rules
  copy:
    src:        "files/99-adafruit-boards.rules"
    dest:       "/etc/udev/rules.d/"
    mode:       0644
    owner:      "public"
    group:      "public"
  register:     udevUpdated

- name: Reload Udev control
  command: udevadm control --reload-rules
  when: udevUpdated == True

- name: Reload udevadmin trigger
  command: udevadm trigger
  when: udevUpdated == True

- name:         Arduino Link on Desktop
  copy:
    src:        "files/desktop/arduino.desktop"
    dest:       "/home/{{item}}/Desktop/"
    mode:       0755
    owner:      "{{ item }}"
    group:      "{{ item }}"
  with_items:
    - "{{arduino_users}}"
  register:     file_copied


- name:         Installing Updated Arduino
  unarchive:
    # src:      "files/{{arduino_version}}-linux64.tar.xz"
    src:        "https://downloads.arduino.cc/{{ arduino_version }}-linux64.tar.xz"
    dest:       /opt/
    remote_src: yes
    creates:   "/opt/{{ arduino_version }}/arduino"

- name:         Create Aruino Global Install
  file:
    src:        "/opt/{{arduino_version}}"
    dest:       "/opt/arduino"
    state:      link
    mode:       0755


- name:         Fixing Permissions Directory
  file:
    path:       "/home/{{item}}/arduino/tools/ArduBlockTool/tool"
    owner:      "{{item}}"
    group:      "{{item}}"
    recurse:    yes
  with_items:
    - "{{arduino_users}}"

- import_tasks:      permissions.yml