---
# Run the equivalent of "apt-get update" as a separate step
- name: Installing required Arduino files
  apt: update_cache=yes name={{item}}
  with_items:
  - arduino
  - arduino-core

- include: permissions.yml

- name: Placing Icon on Desktop of Public User
  copy:
    src: "files/arduino.desktop"
    dest: "/home/public/Desktop/"
    mode: 0755
  register: fonts_copied
