---
# Run the equivalent of "apt-get update" as a separate step
#- apt: update_cache=yes name={{item}}
#  with_items:
#  - arduino
#  - arduino-core

#- include: permissions.yml

- name: ArduBlockTool Creating Directory
  file:
    path: "/home/public/sketchbook/tools/ArduBlockTool/tool/"
    state: directory
    mode: 0755

- name: Placing ArduBlockTool into IDE
  copy:
    src: "files/ardublock-all.jar"
    dest: "/home/public/sketchbook/tools/ArduBlockTool/tool/"
    mode: 0755
  register: file_copied

- name: Fixing Permissions Files
  file: path=/home/public/sketchbook/tools/ArduBlockTool/tool/ardublock-all.jar owner=public group=public mode=0644

- name: Fixing Permissions Directory
  file: path=/home/public/sketchbook/tools/ArduBlockTool/tool owner=public group=public recurse=yes
