---
base_users:
    - name:       public
      comment:    "Public Account"
      createhome: yes
      state:      present
      password:   "{{vault_passwords.public}}"
      groups:     public,adm,cdrom,dip,plugdev,sambashare,libvirtd
    - name:       it
      comment:    "IT Administrative Account"
      createhome: yes
      state:      present
      password:   "{{vault_passwords.it}}"
      groups:     it,adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare,libvirtd,docker
simple_users:
    - it
    - public

base_groups:
    - docker
