---
# Remove Files
- apt: state=absent purge=yes name={{item}}
  with_items:
    - transmission
    - hexchat
    - thunderbird
    - pidgin


- apt: update_cache=yes

# Install Files
- apt: state=present name={{item}}
  with_items:
   # Screensavers
#    - xscreensaver-gl
#    - xscreensaver-gl-extra
#    - xscreensaver-screensaver-dizzy
#    - xscreensaver-screensaver-webcollage
#    - xscreensaver-data-extra
#    - rss-glx
    # Core Desktop Tools
    - python-software-properties
    - htop
    - glances
    - wget
    - curl
    - nano
    - python-pycurl
