---
# Remove Files
- apt: state=absent purge=yes name={{item}}
  with_items:
    - transmission
    - hexchat
    - thunderbird
    - pidgin


- apt: update_cache=yes

# Install Files
- apt: state=present name={{item}}
  with_items:
    # Core Desktop Tools
    - python-software-properties
    - htop
    - glances
    - wget
    - curl
    - nano
    - python-pycurl
