---
# Remove Files
- name: Remove unneeded packages
  apt: state=absent purge=yes name={{ item }}
  with_items:
    - transmission
    - hexchat
    - thunderbird
    - pidgin
    - cron-apt
    - gnome-screensaver

# Install Files
- name: Install needed packages
  apt: state=present name={{ item }}
  with_items:
  # screensaver
  - xscreensaver
  - xscreensaver-gl
  - xscreensaver-gl-extra
  - xscreensaver-screensaver-dizzy
  - xscreensaver-screensaver-webcollage
  - xscreensaver-data-extra
  - rss-glx
  # Core Desktop Tools
  - python-software-properties
  - htop
  - wget
  - curl
  - nano
  - python-pycurl
  - phoronix-test-suite
  - compizconfig-settings-manager
  - firefox
  - unity-tweak-tool
  - python-pip
  - variety
  - tor-browser

#Developer packages. These might end up being in their own groups
  - ubuntu-make
  - qt4-dev-tools
  - build-essential
  - libx11-6
  - libx11-dev
  - libx11-guitest-perl
  - gnome-boxes
  - screen
  - git


#  loop_control:
#    loop_var: install
