---
- name:           Make provision directories
  file:
    path:         "{{item}}"
    state:        directory
    mode:         0755
    recurse:      yes
  with_items:
    - "/opt/provision/"
    - "/opt/provision/bin/"

- name:           Create Groups
  group:
    name:         "{{ item }}"
    state:        present
  with_items:
    - "{{ base_groups }}"

- name:           Create User Accounts
  user:
    name:         "{{ item.name }}"
    state:        "{{ item.state }}"
    comment:      "{{ item.comment }}"
    createhome:   "{{ item.createhome }}"
    password:     "{{ item.password }}"
    generate_ssh_key: yes
  with_items:
    - "{{ base_users }}"

- name:           Copy bashrc file
  copy:
    src:          'files/bashrc'
    dest:         "/home/{{ item }}/.bashrc"
    mode:         0644
    group:        "{{ item }}"
    owner:        "{{ item }}"
  with_items:
    - "{{ simple_users }}"

- name:           Create Directory for wallpapers
  file:
    path:         "/opt/provision/wallpaper/"
    state:        directory
    mode:         0755

- name:           Copy update script and make it executable
  copy:
    src:          files/scripts/autoupdate.sh
    dest:         /etc/cron.daily/
    owner:        root
    group:        root
    mode:         755
    backup:       yes

- name:           Ensure blacklist file exsists
  file:
    path:         /etc/pm/config.d/
    state:        directory

- name:           Ensure blacklist file exsists
  file:
    path:         /etc/pm/config.d/blacklist
    state:        touch

- name:           Ensure wifi Does not turn off
  lineinfile:
    dest:         /etc/pm/config.d/blacklist
    regexp:       "^HOOK_BLACKLIST"
    line:         "HOOK_BLACKLIST=\"wireless\""
    backup:       yes


#install repositories
#- name:           Add repositories for Ubuntu Make
#  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make' state=present

#- name:           Add repositories for tor browser
#  apt_repository: repo='ppa:webupd8team/tor-browser' state=present