---
  #- include: font.yml
#  - include: base16.yml
- name: Include User Variables
  include_vars: users.yml


- name: Create groups before users
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{base_groups}}"


- name: Create Public User
  user:
    state: present
    comment: "Public User"
    name: public
    createhome: yes
    password: "$6$7aUMFzunHBz6eN$YFpmYsvxK.hjtDHxf6cwY9Fe.ujGijvla04gxxKdVDwrrN6pOkKTh3isBsxcAU1MqoZ6Kk3rzJuLBwGtZDX1H."
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd

- name: Create IT User
  user:
    comment: "IT User"
    state: present
    name: it
    createhome: yes
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd,sudo

- name: Create Remote
  user:
    comment: "Remote"
    state: present
    name: remote
    createhome: yes
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd,sudo

- name: Deploy keys
  authorized_key:
    user: it
    key: "{{ lookup('file', '/home/joe/.ssh/remote.pub') }}"
    path: '/etc/ssh/authorized_keys/it'

# - include: "all_gconf.yml"

- name: Autologin Public Create Directory
  file:
    path: "/etc/lightdm/lightdm.conf.d/"
    state: directory
    mode: 0755

- name: Autologin Public User file
  copy:
    src: "files/autologinpublic.conf"
    dest: "/etc/lightdm/lightdm.conf.d/"
    mode: 0755

- name: Copy bashrc file
  copy:
    src: 'files/bashrc'
    dest: "/home/{{ item }}/.bashrc"
    mode: 0644
    group: "{{ item }}"
    owner: "{{ item }}"
  with_items:
    - public
    - it
    - remote

- name: Remote errant bashrc
  file:
    path: "/home/{{ item }}/bashrc"
    state: absent
  with_items:
    - public
    - it
    - remote



- name: Wallpaper Public
  copy:
    src: files/wallpaper/wallpaper.jpg
    dest: /usr/share/backgrounds/publicClassroom.jpg
    mode: 0644

- name: Autologin Public Create Directory
  file:
    path: "/etc/lightdm/lightdm.conf.d/"
    state: directory
    mode: 0755

- name: Autologin Public User file
  copy:
    src: "files/autologinpublic.conf"
    dest: "/etc/lightdm/lightdm.conf.d/"
    mode: 0755

- name: Copy update script and make it executable
  copy: src=files/autoupdate.sh dest=/etc/cron.daily owner=root group=root mode=755 backup=yes
#- name: Give the user access to their .bashrc
#  file:
#    path: /home/"{{ item }}"/.bashrc
#    owner: "{{ item }}"
#    group: "{{ item }}"
#    mode: 0644
#  with_items:
#    - public
#    - it
#    - remote
