---
  #- include: font.yml
#  - include: base16.yml
- name: Include User Variables
  include_vars: users.yml

# @clean up
#- name: remove provision temp directory
#  file:
#    path: "/opt/provision/"
#    state: absent

- name: Make provision temp directory
  file:
    path: "/opt/provision/"
    state: directory
    mode: 0755
    recurse: yes

- name: Create groups before users
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{base_groups}}"


- name: Create Public User
  user:
    state: present
    comment: "Public User"
    name: public
    createhome: yes
    password: "$6$7aUMFzunHBz6eN$YFpmYsvxK.hjtDHxf6cwY9Fe.ujGijvla04gxxKdVDwrrN6pOkKTh3isBsxcAU1MqoZ6Kk3rzJuLBwGtZDX1H."
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd

- name: Create IT User
  user:
    comment: "IT User"
    state: present
    name: it
    createhome: yes
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd,sudo

- name: Create Remote
  user:
    comment: "Remote"
    state: present
    name: remote
    createhome: yes
#    groups: public,adm,cdrom,dip,plugdev,sambashare,libvirtd,sudo

- name: Deploy keys
  authorized_key:
    user: it
    key: "{{ lookup('file', '/home/joe/.ssh/remote.pub') }}"
    path: '/etc/ssh/authorized_keys/it'

# - include: "all_gconf.yml"

- name: Autologin Public Create Directory
  file:
    path: "/etc/lightdm/lightdm.conf.d/"
    state: directory
    mode: 0755

- name: Autologin Public User file
  copy:
    src: "files/autologinpublic.conf"
    dest: "/etc/lightdm/lightdm.conf.d/"
    mode: 0755

- name: Copy bashrc file
  copy:
    src: 'files/bashrc'
    dest: "/home/{{ item }}/.bashrc"
    mode: 0644
    group: "{{ item }}"
    owner: "{{ item }}"
  with_items:
    - "{{ simple_users }}"


- name: Rem errant bashrc
  file:
    path: "/home/{{ item }}/bashrc"
    state: absent
  with_items:
    - "{{ simple_users }}"


- name: Create Directory for wallpapers
  file:
    path: "/opt/provision/wallpaper/"
    state: directory
    mode: 0755

- name: Create Directory for wallpapers users
  file:
    path: "/opt/provision/wallpaper/{{ item }}/"
    state: directory
    mode: 0755
  with_items:
    - "{{ simple_users }}"


- name: Copy Wallpapers
  copy:
    src: "files/wallpaper/{{ item }}.jpg"
    dest: "/opt/provision/wallpaper/{{ item }}/wallpaper1.jpg"
    mode: 0644
  with_items:
    - "{{ simple_users }}"


- name: Autologin Public Create Directory
  file:
    path: "/etc/lightdm/lightdm.conf.d/"
    state: directory
    mode: 0755

- name: Autologin Public User file
  copy:
    src: "files/autologinpublic.conf"
    dest: "/etc/lightdm/lightdm.conf.d/"
    mode: 0755
- name: Copy update script and make it executable
  copy: src=files/autoupdate.sh dest=/etc/cron.daily owner=root group=root mode=755 backup=yes








# systemD
#   _______           _______ _________ _______  _______  ______
#  (  ____ \|\     /|(  ____ \\__   __/(  ____ \(       )(  __  \
#  | (    \/( \   / )| (    \/   ) (   | (    \/| () () || (  \  )
#  | (_____  \ (_) / | (_____    | |   | (__    | || || || |   ) |
#  (_____  )  \   /  (_____  )   | |   |  __)   | |(_)| || |   | |
#        ) |   ) (         ) |   | |   | (      | |   | || |   ) |
#  /\____) |   | |   /\____) |   | |   | (____/\| )   ( || (__/  )
#  \_______)   \_/   \_______)   )_(   (_______/|/     \|(______/
#


- name: Make systemD Folder default.target.wants(1/2)
  file:
    path: "/home/{{ item }}/.config/systemd/user/default.target.wants/"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
    recurse: yes
  with_items:
    - "{{ simple_users }}"

- name: Make systemD Folder Fix Permissions(2/2)
  file:
    path: "/home/{{ item }}/.config/systemd/"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
    recurse: yes
  with_items:
    - "{{ simple_users }}"


# Wallpaper
#            _______  _        _        _______  _______  _______  _______  _______
#  |\     /|(  ___  )( \      ( \      (  ____ )(  ___  )(  ____ )(  ____ \(  ____ )
#  | )   ( || (   ) || (      | (      | (    )|| (   ) || (    )|| (    \/| (    )|
#  | | _ | || (___) || |      | |      | (____)|| (___) || (____)|| (__    | (____)|
#  | |( )| ||  ___  || |      | |      |  _____)|  ___  ||  _____)|  __)   |     __)
#  | || || || (   ) || |      | |      | (      | (   ) || (      | (      | (\ (
#  | () () || )   ( || (____/\| (____/\| )      | )   ( || )      | (____/\| ) \ \__
#  (_______)|/     \|(_______/(_______/|/       |/     \||/       (_______/|/   \__/
#
- name: Copying Wallpaper systemd files (1/2)
  copy:
    src: 'files/services/gnome-background-change.service'
    dest: "/home/{{ item }}/.config/systemd/user"
    mode: 0700
    backup: yes
    group: "{{ item }}"
    owner: "{{ item }}"
  with_items:
    - "{{ simple_users }}"


- name: Copying Wallpaper systemd files (2/2)
  copy:
    src: 'files/services/gnome-background-change.timer'
    dest: "/home/{{ item }}/.config/systemd/user"
    mode: 0700
    backup: yes
    group: "{{ item }}"
    owner: "{{ item }}"
  with_items:
    - "{{ simple_users }}"


- name: Enable wallpaper changing service
  systemd:
    name: "gnome-background-change.timer"
    enabled: yes
    state: started
  become: true
  become_user: "{{ item }}"
  with_items:
    - "{{ simple_users }}"

# Xscreensaver
#            _______  _______  _______  _______  _______  _        _______  _______           _______  _______
#  |\     /|(  ____ \(  ____ \(  ____ )(  ____ \(  ____ \( (    /|(  ____ \(  ___  )|\     /|(  ____ \(  ____ )
#  ( \   / )| (    \/| (    \/| (    )|| (    \/| (    \/|  \  ( || (    \/| (   ) || )   ( || (    \/| (    )|
#   \ (_) / | (_____ | |      | (____)|| (__    | (__    |   \ | || (_____ | (___) || |   | || (__    | (____)|
#    ) _ (  (_____  )| |      |     __)|  __)   |  __)   | (\ \) |(_____  )|  ___  |( (   ) )|  __)   |     __)
#   / ( ) \       ) || |      | (\ (   | (      | (      | | \   |      ) || (   ) | \ \_/ / | (      | (\ (
#  ( /   \ )/\____) || (____/\| ) \ \__| (____/\| (____/\| )  \  |/\____) || )   ( |  \   /  | (____/\| ) \ \__
#  |/     \|\_______)(_______/|/   \__/(_______/(_______/|/    )_)\_______)|/     \|   \_/   (_______/|/   \__/
#
- name: Xscreensaver Service
  copy:
    src: files/services/xscreensaver.service
    dest: "/home/{{ item }}/.config/systemd/user/"
    mode: 0700
    owner: "{{ item }}"
    group: "{{ item }}"
    backup: yes
  with_items:
    - "{{ simple_users }}"

- name: Manually enable Xscreensaver for all users
  file:
    dest: "/home/{{ item }}/.config/systemd/user/default.target.wants/xscreensaver.service"
    src: "/home/{{ item }}/.config/systemd/user/xscreensaver.service"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: link
  with_items:
    - "{{ simple_users }}"


#install repositories
- name: Add repositories for Ubuntu Make
  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make' state=present

- name: Add repositories for tor browser
  apt_repository: repo='ppa:webupd8team/tor-browser' state=present
