---
- name:           Create Groups
  group:
    name:         "{{ item }}"
    state:        present
  with_items:
    - "{{ base_groups }}"

- name:           Create User Accounts
  user:
    name:         "{{ item.name }}"
    state:        "{{ item.state }}"
    comment:      "{{ item.comment }}"
    createhome:   "{{ item.createhome }}"
    password:     "{{ item.password }}"
    generate_ssh_key: yes
  with_items:
    - "{{ base_users }}"

- name:           Copy bashrc file
  copy:
    src:          'files/bashrc'
    dest:         "/home/{{ item }}/.bashrc"
    mode:         0644
    group:        "{{ item }}"
    owner:        "{{ item }}"
  with_items:
    - "{{ simple_users }}"




#install repositories
#- name:           Add repositories for Ubuntu Make
#  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make' state=present

#- name:           Add repositories for tor browser
#  apt_repository: repo='ppa:webupd8team/tor-browser' state=present