---

- name: Include User Variables
  include_vars: users.yml
  
#- name: Running OS specific Configurations and Commands
#  include: "{{ baseCommands }}"
#  with_items:
  # - "{{ ansible_os_family }}_packages.yml"
  # - "{{ ansible_os_family }}_system.yml"
#  loop_control:
#    loop_var: baseCommands

- name: Running generic Configurations and Commands
  include: "{{ genericCommands }}"
  with_items:
  - "all_system.yml"
  - "all_packages.yml"
  - "all_gconf.yml"
  loop_control:
    loop_var: genericCommands

# Referencing the page I used to find out most of this https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html
