---
# The location where the pubkeys can be found.
#users_default_pubkey_location: '{{ playbook_dir }}/files/pubkeys/{{ inventory_hostname }}/'

users_available:
  - username: remote
    uid: 1088
    gid: 129,27
    name: "IT Remote User"
    home: "/home/remote"
    upload_key: True
    auth_file: "foocustom.pub" # define specific pubkey file (otherwise it will assume username.pub)

#users_deleted:
#  - username: barfoo

users_groups_available:
  - groupname: btsync
#    gid: 1050
#  - groupname: sysgroup
#    gid: 801
#    is_system_group: True
